---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:oauth_token: 842167434-9da3bRqbuw6mtXF7QdXkUrMeH9hmE5tUaQMniWCI
:oauth_secret: NA08weFYI2HtgNChqvatmqqE6ICDt43VwTEgjOT1beU
